POST http://localhost:3000/api/sessions
Content-Type: application/json

{
  "type": "solo",
  "candidates": ["John", "Anna", "Bob", "David"],
  "voterCount": 18,
  "song": "Rise up"
}

###
POST http://localhost:3000/api/sessions/6875c4b1df6cd41269091a50/rounds
Content-Type: application/json

{
  "votes": [7, 8, 1, 2]
}

###
POST http://localhost:3000/api/sessions/6875c4b1df6cd41269091a50/rounds
Content-Type: application/json

{
  "votes": [8, 10]
}

###
POST http://localhost:3000/api/sessions/6875c4b1df6cd41269091a50/rounds
Content-Type: application/json

{
  "votes": [8, 8]
}

###
POST http://localhost:3000/api/sessions/6875c4b1df6cd41269091a50/rounds
Content-Type: application/json

{
  "votes": [9, 8]
}

###
GET http://localhost:3000/api/sessions/6875c4b1df6cd41269091a50
